Ljg/mpiarray direct buffer
radiocosmology/caput pull request #218
Opened 2022-09-22 19:48 UTC by ljgray

Modifies `MPIArray.redistribute` method to reduce overall memory use. This is accomplished by:
- Passing messages cyclically to the `i` adjacent neighbour for `i` total ranks. This lets us only have a single copied block of the full array in memory at any time
- Writing received messages directly into the target array rather than using an intermediate buffer, and returning and `MPIArray` view of the final array data

2022-10-29 02:07 UTC, sjforeman commented
I recently ran into an edge case that is relevant here: suppose you are running on a single (cedar) node with multiple MPI processes, and have an MPIArray that fits within the node's memory, but the node does not have enough memory to perform the redistribute operation. In this case, I've consistently been getting an ugly crash, e.g.
```
srun: error: cdr2435: task 0: Killed
srun: launch/slurm: _step_signal: Terminating StepId=49095625.0
slurmstepd: error:  mpi/pmix_v3: _errhandler: cdr2435 [0]: pmixp_client_v2.c:211: Error handler invoked: status = -25, source = [slurm.pmix.49095625.0:0]
```
While this case might be rare in practice (and even rarer after this PR is merged), it would be nice if there were a more informative error message if this occurs.

2022-10-29 03:43 UTC, ljgray commented
I don't think (don't quote me on this) that it would be too difficult to do a check for available memory before doing the redistribute and to throw a memory error if there isn't enough memory for it. Also, I suppose that `.redistribute` could delete each array chunk after it's been sent, which would further reduce the amount of memory required. @jrs65 do you see any reason why this could be a bad idea, given that it uses SendRecv so the message is guaranteed to have already arrived?

2022-11-01 18:36 UTC, ljgray commented
I've added a method to check for available space in `mpiutil` and included a check in `redistribute`. This will only really work if the job has a full node allocation, since all of the available memory is visible but not necessarily allocated, and there isn't really a good to way to figure out the allocation (the code would have to have knowledge of its slurm jod ID). I would expect to get a slurm out-of-memory error when it kills a job though.

2022-11-08 19:43 UTC, jrs65 requested changes

2022-11-08 19:43 UTC, jrs65 commented on caput/tests/test_mpiarray.py
> +    assert arr.local_array.flags.c_contiguous
Yeah, good, we should test this one.

2022-11-08 19:47 UTC, ljgray commented on caput/mpiarray.py
> +        return mpiutil.allreduce(self.local_array.nbytes)
I had actually just meant to remove this, I thought it might be needed for the memory check but didn't end up using it.

2022-11-08 19:49 UTC, ljgray commented on caput/mpiarray.py
> +        if not mpiutil.can_allocate(min_req_mem, scope="process", comm=self.comm):
It isn't ideal, but at least it's a bit more informative when jobs do die

2022-11-08 19:51 UTC, ljgray commented on caput/mpiarray.py
> +        min_req_mem = int((1 + 4 / self.comm.size) * self.local_array.nbytes)
Just padding since the memory measurement isn't perfect. The 4 is arbitrary

2022-11-08 19:53 UTC, ljgray commented on caput/mpiarray.py
> +                buffer = np.empty(buffer_shape, dtype=self.dtype)
Good suggestion, not sure if it will make much difference in speed but I can definitely see it being more robust

2022-11-09 23:52 UTC, ljgray commented
Notes to self:
- Processes running in a virtual environment have a different PID from the parent process (i.e. that PID won't match what we're looking for in /proc), so, for example, we have to take `psutil.Process(os.getpid()).parent().pid`.
- Trying to get `memory_full_info()` for the parent results in a permission error, but we can still read `/proc/<pid>/cgroup` and files in /sys/fs/cgroup/memory/<cgroup>/memory.*.
- Fetching <cgroup> from /proc/<pid>/cgroup just returns `/system.slice/slurmd.service`. This is the same for all processes across all nodes.
- `hierarchical_memory_limit` is `9223372036854771712`, or `9.2e18`. This seems to have the same value across all nodes/processes, and is the same as the values in `memory.soft_limit_in_bytes` and `memory.limit_in_bytes`. It's also the same as what we see when looking at `memory.stat` from a login node with `<cgroup_path> = /`.

2022-11-10 22:00 UTC, ljgray commented on caput/mpiutil.py
> +
It seems like all processes share a memory limit. 

Processes have cgroups of, for example, /slurm/uid_3120084/job_50111517/step_0/task_3. 
The main batch job memory info would be under /slurm/uid_3120084/job_50111517/step_batch. Generally this is the same as the memory seen by the individual processes, unless for whatever reason there was a job step with a different allocation.

2022-11-11 01:37 UTC, ljgray commented
I'm going to play around with this a bit more to make sure there are no bugs with the way its checking for available memory.

2022-11-15 00:35 UTC, ljgray commented
Seems to work fine but making the shared comm in `can_allocate` is very expensive (around 40% of the total time spent in redistribute) so its probably worth finding a way to avoid using it

2022-11-17 23:04 UTC, jrs65 requested changes
@ljgray I added some comments about places the new code would break. I don't think it necessarily needs to attempt to get the info from the cgroups in cgroups v2 (just using `.available` from psutil is fine) but it can't break which it currently will do.

2022-11-17 23:04 UTC, jrs65 commented on caput/mpiutil.py
> +    memorystat = open(f"/sys/fs/cgroup/memory/{cgroup}/memory.stat").read()
Also, I think for cgroups v2 `memory.stat` does not contain the information you want and `memory.usage_in_bytes` doesn't exist.

2022-11-17 23:04 UTC, jrs65 commented on caput/mpiutil.py
> +    memorystat = open(f"/sys/fs/cgroup/memory/{cgroup}/memory.stat").read()
See `tubular` as an example of a node running cgroup v2.

2022-11-17 23:05 UTC, jrs65 commented
We might want to have the CI running the tests on macOS too. At least then you'd have had some tests fail with the most recent commit.

2022-11-17 23:09 UTC, jrs65 commented on caput/mpiutil.py
> +        return psutil.virtual_memory().available
Ultimately it's also not best practice to just `open(...).read(...)` a file. What if it doesn't exist? (which is the key issue in here)

2022-11-18 00:08 UTC, ljgray commented on caput/mpiutil.py
> +    memorystat = open(f"/sys/fs/cgroup/memory/{cgroup}/memory.stat").read()
I think that the `findall` for `memory:` would be empty for cgroup v2, which would in turn return `.available` from psutil and these lines wouldn't be executed. It's still worth adding better error handling around these, and making sure that `.available` would actually be correct for cgroup v2.

2023-03-08 18:30 UTC, jrs65 approved these changes

2023-03-08 18:39 UTC, merged