Pipeline tasks can return multiple outputs to unpack
radiocosmology/caput pull request #263
Opened 2024-02-06 01:09 UTC by jrs65

- test(pipeline): ensure multiple output pipeline tasks are supported
- fix(pipeline): pipeline tasks can return multiple outputs to unpack

2024-02-06 23:18 UTC, rikvl requested changes
Hope I understood what's going on here. If so, I think this only requires one or two small changes.

2024-02-06 23:18 UTC, rikvl commented on caput/tests/conftest.py
> +      in: egg
```suggestion
      in: color
```
Not 100% sure if I understood the intention of this test. Were the same eggs supposed to be fried twice? If the idea was to test a task with multiple outputs, where the outputs get used by subsequent tasks, then I think `color` should be an input somewhere.

2024-02-06 23:18 UTC, rikvl commented on caput/tests/test_pipeline.py
> +    """Test running a very simple pipeline."""
```suggestion
    """Test running a very simple pipeline with a multiple-outputs task."""
```

2024-08-06 17:51 UTC, ljgray commented
The key functionality here was added in a different PR, so this is now just adding tests

2024-08-06 18:00 UTC, ketiltrout approved these changes
This seems fine.

Though, `import`ing `conftest` directly, instead of just setting up a bunch of fixtures is a weird way of doing things.  But I don't think this PR is the place to address that.

2024-08-06 18:03 UTC, merged